Chapter 03. 신경망 (part 2)
hfpsych lab workshop
2019.7.23 Tue. Yoon Kyung Lee

## 3.3 다차원 배열의 계산 
### 3.3.1 다차원 배열
### 3.3.2. 행렬의 곱
### 3.3.3. 신경망에서의 행렬 곱
## 3.4. 3층 신경망 구현하기
### 3.4.1. 표기법 설명
### 3.4.2. 각 층의 신호 전달 구현하기
### 3.4.3. 구현 정리
----
(금요일에 이어서 )
## 3.5. 출력층 설계하기
### 3.5.1. 항등 함수와 소프트맥스 함수 구현하기
### 3.5.2. 소프트맥스 함수 구현 시 주의점
### 3.5.3. 소프트맥스 함수의 특징
### 3.5.4. 출력층의 뉴런 수 정하기


<a id = 'section 3.3'></a>

### 3.3. 다차원 배열의 계산

넘파이의 다차원 배열을 사용한 계산법을 숙달하면 신경망을 효율적으로 구현할 수 있다. 

### 3.3.1. 다차원 배열

지금까지 보아온 1차원 배열은 다음과 같다

In [1]:
import numpy as np
A = np.array([1,2,3,4])
print(A)

[1 2 3 4]


In [2]:
np.ndim(A) #배열의 차원수는 np.ndim()함수로 확인할 수 있다. 

1

In [3]:
A.shape #또한 배열의 형상은 인스턴스 변수인 shape로 알 수 있다. 

(4,)

In [4]:
A.shape[0] 

4

2차원 배열을 반환해보자

In [0]:
B = np.array([[1,2],[3,4],[5,6]])

In [7]:
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
np.ndim(B)

2

In [10]:
B.shape #3x2 배열인 B를 작성했다. 

(3, 2)

3x2 배열은 처음 차원에는 원소가 3개, 다음 차원에는 원소가 2개 있다는 의미이다. 이때 처음 차원은 0번째 차원, 다음 차원은 1번째 차원에 대응한다 (파이썬의 인덱스는 0부터 시작한다)

2차원 배열은 특히 행렬<sup>matrix</sup>이라고 부른다. 

### 3.3.2. 행렬의 곱

### 그림 3-11. 행렬의 곱

행렬 곱은 왼쪽 행렬의 행(가로)과 오른쪽 행렬의 열(세로)을 원소별로 곱하고 그 값들을 더해서 계산한다. 그 계산 결과가 새로운 다차원 배열의 원소가 된다. 

예를 들어 A의 1행과 B의 1열을 곱한 값은 결과 행렬의 1행 1번째 원소가 되고, A의 2행과 B의 1열을 곱한 결과는 2행 1번째 원소가 된다. 

파이썬으로 구현한 행렬의 곱

In [11]:
A = np.array([[1,2],[3,4]])
A.shape

(2, 2)

In [0]:
B = np.array([[5,6],[7,8]])

In [13]:
B.shape

(2, 2)

In [14]:
np.dot(A,B) #A와 B는 2x2행렬이며, 두 행렬의 곱은 넘파이 함수 np.doct()으로 계산한다

array([[19, 22],
       [43, 50]])

np.dot()은 입력이 1차원 배열이면 벡터를, 2차원 배열이면 행렬 곱을 계산한다. 

np.dot(A,B)와 np.dot(B,A)는 다른 값이 될 수 있다. +와 * 등의 일반적인  연산과 달리 행렬의 곱에서는 피연산자의 순서가 다르면 결과도 다르다. 

행렬 A의 1번째 차원의 원소 수 (열 수)와 행렬  B의 0번째 차원의 원소 수(행 수)가 같아야한다. 
2x3의 A와 2x2행렬 C를 곱하면 오류가 난다. 

2x3 행렬과 3x2 행렬의 곱을 파이썬으로 구현해보아라 

## 실습 

실습 자료 결과 값을 자신의 깃헙 레포지토리에 저장하고 링크를 제출하시오 

레포지토리 이름 : hfpsych_workshop
폴더명:DeepNLP
파일명: w4_neuralnet_part2_본인이름.ipynb

제출방법: 깃헙 레포지토리 > 폴더 안에 커밋되어있는 ipynb노트북 링크를 슬랙 sum19_study에 공유하여 제출 


1번

In [0]:
#A 정의 

In [17]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
#B 정의

In [20]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
#A와 B의 행렬 곱 


array([[22, 28],
       [49, 64]])

2번. 아래 연산이 오류가 나지 않게 B를 고쳐보시오

In [0]:
A = np.array([[1,2],[3,4],[5,6]])
A.shape

In [0]:
B = np.array([[7,8]]]) #고쳐보기 
B.shape

In [0]:
np.dot(A,B) #출력에 오류가 없어야함

### 3.3.3. 신경망에서의 행렬 곱

#### 그림 3.14 행렬의 곱으로 신경망의 계산을 수행한다

In [36]:
X = np.array([1,2])
X.shape

(2,)

In [37]:
W = np.array([[1,3,5], [2,4,6]])
print(W)

[[1 3 5]
 [2 4 6]]


In [38]:
W.shape

(2, 3)

In [0]:
Y = np.dot(X,W)

In [40]:
print(Y)

[ 5 11 17]


### 3.4. 3층 신경망 구현하기

#### 그림 3-15. 3층 신경망

#### 3.4.1. 표기법 설명

_w_<sub>12</sub><sup>(1)</sup>, _a_<sup>(1)</sup><sub>1</sub>

#### 그림 3-16 중요한 표기


### 3.4.2. 각 층의 신호 전달 구현하기

In [0]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
B1 = np.array([0.1,0.2,0.3])

In [0]:
#X 크기 확인 (힌트: .shape )


In [0]:
#W1 크기 확인

In [0]:
#B1 크기 확인

In [0]:
A1 =  # X와 W1의 행렬 연산 + B1 (bias)

#### 그림 3-18. 입력층에서 1층으로 신호 전달

그림 3-18과 같이 은닉층에서의 가중치 합(가중 신호와 편향의 총합)을 a로 표기하고 활성화 함수 h( )로 변환된 신호를 z로 표기한다. 여기에서는 활성화 함수로 시그모이드 함수를 사용하기로 해보자.


In [0]:
#시그모이드 함수
def sigmoid(x):
    return 1 / (1 + np.exp(-x)) 

In [50]:
Z1 = sigmoid(A1)

print(A1) #앞에서 A1 출력값을 얻어내야 계산이 가능하다

[0.3 0.7 1.1]


In [51]:
print(Z1)

[0.57444252 0.66818777 0.75026011]


#### 그림 3-19. 1층에서 2층으로의 신호 전달


In [0]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([[0.1, 0.2]])

In [54]:
print(Z1.shape)

(3,)


In [55]:
print(W2.shape)

(3, 2)


In [56]:
print(B2.shape)

(1, 2)


In [0]:
A2 = np.dot(Z1, W2) + B2 #1층에서 2층으로의 신호 총합(전달)

In [0]:
Z2 = sigmoid(A2)

In [59]:
Z2

array([[0.62624937, 0.7710107 ]])

#### 그림 3-20. 2층에서 출력층으로의 신호 전달

출력층의 활성화 함수를 &sigma; ()로 표시하여 은닉층의 활성화 함수 _h_()와는 다름을 명시하였음

In [0]:
def identity_function(x): #항등 함수 = 입력을 그대로 출력하는 함수
  return x

In [0]:
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([[0.1, 0.2]])

In [0]:
A3 = np.dot(Z2, W3) + B3

In [0]:
Y = identity_function(A3) #or Y = A3

In [67]:
Y

array([[0.31682708, 0.69627909]])

### 3.4.3. 구현 정리
 
 순방향 신경망 구현!

In [78]:
def init_network(): #가중치와 편향을 초기화 + 딕셔너리 변수인 network에 저장
  network = {} #딕셔너리 변수인 network에 각 층에 필요한 매개변수(가중치와 편향)을 저장
  network['W1'] = np.array([[0.1,0.3,0.5],[0.2,0.4,0.6]])
  network['b1'] = np.array([[0.1,0.2,0.3]])
  network['W2'] = np.array([[0.1,0.4],[0.2,0.5],[0.3,0.6]])
  network['b2'] = np.array([[0.1,0.2]])
  network['W3'] = np.array([[0.1,0.3],[0.2,0.4]])
  network['b3'] = np.array([[0.1,0.2]])
  
  return network

def forward(network, x): #입력 신호를 출력으로 변환하는 처리 과정 
  W1, W2, W3 = network['W1'], network['W2'], network['W3']
  b1, b2, b3 = network['b1'], network['b2'], network['b3']
  
  a1 = np.dot(x, W1) + b1
  z1 = sigmoid(a1)
  a2 = np.dot(z1, W2) + b2
  z2 = sigmoid(a2)
  a3 = np.dot(z2, W3) + b3
  y = identity_function(a3)
  
  return y

network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
print(y) #[0.31682708, 0.69627909]


[[0.31682708 0.69627909]]
